# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20171201_2218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
