# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171202_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientstep',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(help_text='Cooking time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.IntegerField(help_text='Preparation time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_count',
            field=models.IntegerField(default=1),
        ),
    ]
