# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171202_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientstep',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientstep',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='preparationstep',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient_info',
            field=models.TextField(default='Info', help_text='Info about what ingredients are required in order to cook the recipe.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_info',
            field=models.TextField(default='Info', help_text='Detailed description of what to do to cook the recipe.'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientStep',
        ),
        migrations.DeleteModel(
            name='PreparationStep',
        ),
    ]
